### ISSUE TITLE
BetTypes are wrong

### ISSUE THREAD

**Issue by dmitrijsc** [anderj017/pinnaclewrapper#3]
Hello

BetType enums do not correspond to the ones listed by Pinnacles.

For example, it should be Total_Points instead of TotalPoints.

https://github.com/anderj017/pinnaclewrapper/blob/master/Enums/BetType.cs
https://www.pinnacle.com/en/api/manual#BET_TYPE

**Comment by darkusone** [comment]
is ok i think, see new api reference http://www.pin8899.com/static/index.php/en-us/help/api-user-guide-en-us#BET_TYPE
